In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_boston, load_iris

from sklearn.linear_model import Ridge,Lasso,ElasticNet, LinearRegression
from sklearn.preprocessing import PolynomialFeatures
from sklearn.pipeline import make_pipeline, Pipeline

from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score

import mglearn
import matplotlib.pyplot as plt
import matplotlib
matplotlib.rcParams['font.family']='Malgun Gothic'
matplotlib.rcParams['axes.unicode_minus'] = False

import warnings
warnings.simplefilter('ignore')

In [2]:
train_df = pd.read_excel('data4/hyundaiCar.xlsx', sheet_name='train')
test_df = pd.read_excel('data4/hyundaiCar.xlsx', sheet_name='test')

In [3]:
x_train = train_df.iloc[:, 1:]
y_train = train_df['가격']

In [4]:
x_train

      년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015  준중형  11.8  172  21.0  가솔린      0  1999  1300  자동
1   2015  준중형  12.3  204  27.0  가솔린      0  1591  1300  자동
2   2015   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
3   2014   소형  14.0  140  17.0  가솔린      0  1591  1090  자동
4   2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
..   ...  ...   ...  ...   ...  ...    ...   ...   ...  ..
66  2015   중형   8.5  290  34.8  가솔린      0  3342  1901  자동
67  2012   소형  13.3  108  13.9  가솔린      0  1396  1040  자동
68  2015  준중형  12.8  186  41.0   디젤      0  1995  1665  자동
69  2015   중형  17.7  156  19.3  가솔린      1  1999  1585  자동
70  2015   대형  13.8  202  45.0   디젤      0  2199  1691  자동

[71 rows x 10 columns]

In [5]:
y_train

0     1885
1     2190
2     1135
3     1645
4     1960
      ...
66    3802
67    1270
68    2430
69    2870
70    3254
Name: 가격, Length: 71, dtype: int64

In [6]:
x_test = test_df.iloc[:, 1:]
y_test = test_df['가격']

In [7]:
x_test

      년식   종류    연비   마력    토크   연료  하이브리드   배기량    중량 변속기
0   2015   대형   6.8  159  23.0  LPG      0  2359  1935  수동
1   2012   소형  13.3  108  13.9  가솔린      0  1396  1035  자동
2   2015   중형  14.4  184  41.0   디젤      0  1995  1792  자동
3   2015   대형  10.9  175  46.0   디젤      0  2497  2210  수동
4   2015   대형   6.4  159  23.0  LPG      0  2359  1935  자동
5   2015   소형  18.0  136  30.6   디젤      0  1582  1160  자동
6   2015  준중형  13.9  184  41.0   디젤      0  1995  1611  수동
7   2015   대형   8.9  133  26.5   디젤      0  2497  1696  수동
8   2015  준중형  12.5  184  41.0   디젤      0  1995  1611  자동
9   2015  준중형  12.8  215  21.3  가솔린      0  1999  1216  수동
10  2015   중형  11.6  168  20.5  가솔린      0  1999  1460  자동
11  2015   중형   8.9  290  34.8  가솔린      0  3342  1832  자동
12  2015   소형  18.0  136  30.6   디젤      0  1582  1190  자동
13  2015  준중형  16.2  128  28.5   디젤      0  1582  1305  자동
14  2015   대형   8.6  282  35.4  가솔린      0  3342  1970  자동
15  2015   소형  19.0  136  30.6   디젤      0  1582  1190  수동
16  2015  준중형  14.4  184  41.0   디젤      0  1995  1548  수동
17  2015   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
18  2014   소형  14.1  100  13.6  가솔린      0  1368  1035  자동
19  2015  준중형  12.4  204  27.0  가솔린      0  1591  1300  수동
20  2014   소형  15.0  100  13.6  가솔린      0  1368  1035  수동
21  2015  준중형  13.0  140  17.0  가솔린      0  1591  1225  수동
22  2015   대형   7.4  416  52.0  가솔린      0  5038  2145  자동
23  2015  준중형  11.8  172  21.0  가솔린      0  1999  1325  자동
24  2015  준중형  12.4  215  21.3  가솔린      0  1999  1216  자동
25  2015  준중형  14.0  140  17.0  가솔린      0  1591  1210  자동
26  2015   대형   8.9  334  40.3  가솔린      0  3778  1915  자동
27  2015   대형   8.7  175  46.0   디젤      0  2497  2383  수동
28  2015   대형   9.6  175  46.0   디젤      0  2497  1990  자동
29  2010   소형  13.0   95  12.7  가솔린      0  1399  1046  자동
30  2015   중형  14.8  200  43.0   디젤      0  2199  1760  수동

In [8]:
y_test

0      1915
1      1164
2      2817
3      2160
4      1915
5      1560
6      2260
7      1430
8      2260
9      1690
10     2255
11     3590
12     1445
13     1610
14     4897
15     1445
16     2080
17     1135
18     1111
19     2190
20     1111
21     1845
22    14570
23     1890
24     1690
25     1410
26     6910
27     2545
28     1960
29      870
30     2879
Name: 가격, dtype: int64

# 문자열 encoding

## label encoding

## one hot encoding

In [9]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder

In [10]:
x_train['종류']

0     준중형
1     준중형
2      소형
3      소형
4      대형
     ...
66     중형
67     소형
68    준중형
69     중형
70     대형
Name: 종류, Length: 71, dtype: object

### Label Encoder

In [11]:
lbl = LabelEncoder()
x_trainLabel = lbl.fit_transform(x_train['종류'])
x_trainLabel

array([2, 2, 1, 1, 0, 3, 3, 1, 3, 1, 2, 3, 2, 0, 1, 0, 0, 0, 3, 0, 0, 3,
       2, 0, 3, 3, 3, 1, 1, 2, 0, 0, 0, 0, 1, 0, 2, 0, 2, 1, 1, 1, 0, 0,
       0, 2, 1, 0, 2, 1, 3, 3, 0, 2, 2, 0, 3, 2, 0, 0, 2, 0, 1, 0, 0, 1,
       3, 1, 2, 3, 0])

In [12]:
lbl.classes_

array(['대형', '소형', '준중형', '중형'], dtype=object)

In [13]:
lbl.classes_[2]

'준중형'

In [14]:
lbl.transform(['소형'])

array([1])

### OneHotEncoder (0과 1로 구성)

In [15]:
oneH = OneHotEncoder()
x_trainOne = oneH.fit_transform(x_train['종류'].values.reshape(-1,1))
x_trainOne

<71x4 sparse matrix of type '<class 'numpy.float64'>'
	with 71 stored elements in Compressed Sparse Row format>

In [16]:
type(x_trainOne)

scipy.sparse.csr.csr_matrix

In [17]:
x_trainOne.toarray()

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 1., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.]])

In [18]:
oneH.categories_

[array(['대형', '소형', '준중형', '중형'], dtype=object)]

### 판다스 dummy

In [19]:
pd.get_dummies(x_train['종류'])

    대형  소형  준중형  중형
0    0   0    1   0
1    0   0    1   0
2    0   1    0   0
3    0   1    0   0
4    1   0    0   0
..  ..  ..  ...  ..
66   0   0    0   1
67   0   1    0   0
68   0   0    1   0
69   0   0    0   1
70   1   0    0   0

[71 rows x 4 columns]

In [20]:
# pd.get_dummies(x_train)
pd.get_dummies(x_train, columns=['연료', '변속기'])

,년식,종류,연비,마력,토크,하이브리드,배기량,중량,연료_LPG,연료_가솔린,연료_디젤,변속기_수동,변속기_자동
0,2015,준중형,11.8,172,21.0,0,1999,1300,0,1,0,0,1
1,2015,준중형,12.3,204,27.0,0,1591,1300,0,1,0,0,1
2,2015,소형,15.0,100,13.6,0,1368,1035,0,1,0,1,0
3,2014,소형,14.0,140,17.0,0,1591,1090,0,1,0,0,1
4,2015,대형,9.6,175,46.0,0,2497,1990,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
66,2015,중형,8.5,290,34.8,0,3342,1901,0,1,0,0,1
67,2012,소형,13.3,108,13.9,0,1396,1040,0,1,0,0,1
68,2015,준중형,12.8,186,41.0,0,1995,1665,0,0,1,0,1
69,2015,중형,17.7,156,19.3,1,1999,1585,0,1,0,0,1
70,2015,대형,13.8,202,45.0,0,2199,1691,0,0,1,0,1

### replace

In [21]:
x_train['종류'].replace(['대형', '중형', '준중형', '소형'], [0,1,2,3])

0     2
1     2
2     3
3     3
4     0
     ..
66    1
67    3
68    2
69    1
70    0
Name: 종류, Length: 71, dtype: int64

## make_column_transformer

In [22]:
from sklearn.compose import make_column_transformer

In [23]:
myt = make_column_transformer((OneHotEncoder(), ['종류', '연료', '변속기']))
result = myt.fit_transform(x_train)
result

array([[0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [0., 0., 1., 0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 1., 0.],
       [0., 0., 0., 1., 0., 0., 1., 1., 0.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.],
       [1., 0., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 1., 0., 1.],
       [0., 0., 0., 1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1., 0., 1.]])

In [24]:
# model = Pipeline([('myt', myt), ('scl', StandardScaler()), ('clf', Ridge())])
model = make_pipeline(myt, PolynomialFeatures(degree=2), StandardScaler(), ElasticNet())
param_value = {'elasticnet__alpha': [0.001, 0.01, 1, 2, 3], 'elasticnet__l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]}
gridS = GridSearchCV(model, param_grid=param_value, scoring='r2')
gridS.fit(x_train, y_train)

GridSearchCV(estimator=Pipeline(steps=[('columntransformer',
                                        ColumnTransformer(transformers=[('onehotencoder',
                                                                         OneHotEncoder(),
                                                                         ['종류',
                                                                          '연료',
                                                                          '변속기'])])),
                                       ('polynomialfeatures',
                                        PolynomialFeatures()),
                                       ('standardscaler', StandardScaler()),
                                       ('elasticnet', ElasticNet())]),
             param_grid={'elasticnet__alpha': [0.001, 0.01, 1, 2, 3],
                         'elasticnet__l1_ratio': [0.1, 0.3, 0.5, 0.7, 0.9]},
             scoring='r2')

In [25]:
gridS.best_params_

{'elasticnet__alpha': 1, 'elasticnet__l1_ratio': 0.3}

In [26]:
gridS.best_score_

0.43816840316685557

In [27]:
gridS.best_estimator_

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['종류', '연료', '변속기'])])),
                ('polynomialfeatures', PolynomialFeatures()),
                ('standardscaler', StandardScaler()),
                ('elasticnet', ElasticNet(alpha=1, l1_ratio=0.3))])

In [28]:
xd = np.array([[2015, '준중형', 12.3, 204, 27, '가솔린', 0, 1591, 1300, '자동']])
xdataF = pd.DataFrame(xd, columns = x_test.columns)
display(xdataF)
gridS.best_estimator_.predict(xdataF)

     년식   종류    연비   마력  토크   연료 하이브리드   배기량    중량 변속기
0  2015  준중형  12.3  204  27  가솔린     0  1591  1300  자동

array([2219.16922673])